### ISSUE TITLE
Returning from Array#forEach

### ISSUE THREAD

**Issue by SidneyNemzer** [genie-team/graphql-genie#10]
I noticed this code in the auth plugin:

https://github.com/genie-team/graphql-genie/blob/fa8f88ae40549a8afde5daaaa0594c200f98116c/plugins/authentication/src/authentication.ts#L291-L296

I don't think that's doing what you meant, is it? Returning from `forEach`  does nothing! Perhaps it's not actually a problem and I'm miss-interpreting it.

Anyway, thanks for working on this awesome GraphQL library!

**Comment by acoreyj** [comment]
hmm yea I'm sure I meant it to return false from the `checkArgsFromResolver` function but I think you are right that it won't work that way. I'll check it out, probably means I missing a test to cover something as well.

**Comment by acoreyj** [comment]
Thanks for the catch and compliment, hoping to share the library more widely soon and catching these sorts of things now is great.

Looks like it was missed by tests because most of my tests I was just throwing errors in the user code so it was never getting to that part of the plugin code on the failures I had. Added some tests to cover the boolean case.
