### ISSUE TITLE
CRUD permission on fields?

### ISSUE THREAD

**Issue by SidneyNemzer** [genie-team/graphql-genie#11]
(Please label as question)

Just a quick question, is there any reason to set create and delete permissions on individual fields? Maybe the field is nullable and create/delete are adding a value or setting it to null? What is your experience?

**Comment by acoreyj** [comment]
Well graphql will error if you ever attempt to set a non-nullable field to null so that shouldn't be an issue.

Yup, some of the major reasons I have used is for instance users shouldn't be able to delete their username or email but maybe could delete other things off of their profile. 

Or you may have a conditional field on a user isAdmin that only admins should be able to create a value for.

Generally create/delete field permissions tend to be things that you want to be possible if you are an admin or have some special permissions that are higher than the rest of the fields on that type.

**Comment by SidneyNemzer** [comment]
Got it, thanks!
