### ISSUE TITLE
Is there an easy way to integrate own Resolvers and SchemaDirectives into GraphQL Genie before an (executable) schema is created?

### ISSUE THREAD

**Issue by yostools** [genie-team/graphql-genie#14]
I looked at the example in the authentication plugin. This includes new Directives (e.g. `auth`), but this is very cumbersome and doesn't work with `graphql-tools` in version `14.0.2` anymore: `Error: Unknown directive "auth".`

**Comment by acoreyj** [comment]
It isn't supported right now to pass in an existing schema and just alter it. I know graphql-tools does have some new features for [schema stiching](https://www.apollographql.com/docs/graphql-tools/schema-stitching.html) to merge schemas though, would that work for your use case?

The other option would be doing it after the fact using the way plugins do it, `addtypedefstoschema` and `setIResolvers` [functions](https://github.com/genie-team/graphql-genie/blob/master/docs/GraphQLGenieAPI.md#addtypedefstoschema). 

I'll look into the `unkown directive "auth"`. Not sure if its something that I can do or if `graphql-tools` doesn't support 14

**Comment by acoreyj** [comment]
Looks like Graphql 14 was validating the directives, so I had to add some logic to temporarily add the directives until the plugin actually sets it up, so that fixes that issue.

If schema stitching is too much trouble it still may be easier to add things after the fact.

For directives you can always do have the directive in your typedefs and then use the `SchemaDirectiveVisitor.visitSchemaDirectives` [function](https://www.apollographql.com/docs/graphql-tools/schema-directives.html).

For resolvers you can use [addResolveFunctionsToSchema](https://www.apollographql.com/docs/graphql-tools/resolvers.html#addResolveFunctionsToSchema)
