### ISSUE TITLE
Is amazing graphql-genie production ready?

### ISSUE THREAD

**Issue by ansarizafar** [genie-team/graphql-genie#18]
@acoreyj Thanks for creating such an amazing project. This project has a great potential to make developers life easy.  I want to use graphql-genie with sapperjs https://sapper.svelte.technology/ and mongodb for my new project but I have few concerns

- Is graphql-genie production ready?
- Is there any roadmap for future development?
- Graphql has n+1 request problem and fortunejs mongodb adptor is using multiple find statements for related documents which means multiple database roundtrip https://github.com/fortunejs/fortune-mongodb/issues/21#issuecomment-428655260. Performance of Nested queries is my main concern. Other similar projects like https://www.graphile.org/graphile-build/look-ahead/ are using single database query for nested graphql queries. We can try to convince fortunejs author to use single mongodb aggregation pipeline with $lookup operator for finding the related documents to avoid multiple database roundtrips but ideally, a great project like graphql-genie shouldn't be dependent on any third party module for data access. I know its lots of work but I think it will greatly improve query performance. Fortunejs mongodb adapter is also lacking support for transactions and data aggregations.

We should have a project/documentation website for such an amazing project and a discoed server for community support.

**Comment by acoreyj** [comment]
Hey!

I wouldn't say it is production ready yet, there has not been a lot of actual use yet since it is so new. Almost to a point where I will share it more widely which will help. I plan on using it in a production (although low risk) project later this year.

There is a bit of a road map in the main Readme

As far as performance that is a concern that genie doesn't attempt to fix at this point, other than making sure the same data isn't requested twice per request. I added a roadmap something I plan to change to make sure if an adapter can optimize a request such as how postgraphile does Genie will properly send it the right  information to do so and will properly handle the response. So in short it will be up to the database adapter to handle keeping requests to a minimum.

I am a big fan of reinventing the wheel, I think fortune is great but do agree some of the adapters could be upgraded for performance and enabling transactions.

Definitely have plans to create a website eventually, Discord is in works
