### ISSUE TITLE
Unexpected Non-Nullable List Behavior

### ISSUE THREAD

**Issue by ecwyne** [genie-team/graphql-genie#3]
**Describe the bug**
Given the schema below, I am unable to create a `User` with an empty `posts` list. Either a `posts.create` or `posts.connect` is required for the mutation. Perhaps a `posts.empty` would do the trick.

**To Reproduce**
```graphql
# typeDefs
type User @model {
  id: ID!
  name: String!
  posts: [Post]! @relation(name: "author")
}

type Post @model {
  id: ID!
  content: String!
  authors: User! @relation(name: "author")
}
```

```graphql
# mutation
mutation {
  createUser(input: {data: {name: "Eric"}}) {
    data {
      name
      posts {
        content
      }
    }
  }
}
```

- Genie Version: 0.3.5
- Fortune Adapter: In Memory

**Expected behavior**
I would expect to create a User with `posts: []`. 

**Additional context**
I realize I can have the list as `Nullable`, however I think that `posts: []` is a much more sensible response than `posts: null` (then I have to check if posts exists before using it every time)

**Comment by acoreyj** [comment]
I agree you should be able to create an empty array here.

I guess the question is if that should have to be explicit (such as use suggest with `posts.empty`) or if we make the PostsCreate...Input field optional and default to an empty array.

Thoughts

**Comment by yostools** [comment]
@acoreyj I would prefer to make the PostsCreate...Input field optional and default to an empty array because I can only think of one reason why `null` would provide additional information compared to an empty array. An empty array could mean that there were ever items that were then deleted, and `null` could mean that there were never any posts. However, if it is possible to explicitly set posts to `null` after the user has been created, then it is also possible to map this very rare case and we have a better default value due to the empty array, without having to explicitly specify `posts.empty`.

**Comment by acoreyj** [comment]
Yea probably best to default to an empty array and not require inputs for non-null list fields. 

Actually due to how fortune works any list field will never be null in the actual data so this should be a pretty basic change, I'll just have to investigate a bit how I'm handling empty arrays during queries.
